version: '3.8'
services:
  dash-app:
    container_name: appseed_app
    image: pmoracho/dash-app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    image: "nginx:latest"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - dash-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
